language: java

script:
- mvn compile
- mvn test
- mvn package
- mvn verify

deploy:
  provider: heroku
  api_key:
    secure: 21386149-88a1-47a2-b52b-0bf74ddd321a
  app: cryptic-sea-87490 

branches:
  only:
    - master




